### ISSUE TITLE
elf relocation vs position indepented code

### ISSUE THREAD

**Issue by Maschell** [wiiu-env/WiiUPluginSystem#1]
# **The problem:**
Multiple plugins will be loaded into memory, this mean that every plugin will be at a different location.
To be able to use them at the same time and in arbitrary combination / order the plugin should able to run where ever they are in memory.

# Possible solution
So far we have (at least) 2 differents solutions for this.

## **Position independet code:**
It is possible to tell the compiler to create position independet code. 
Currently it's unkown if it's actually supported by the compiler and how good it's working

Pro:
- easy, just set a compiler flag. (-fpic)

Con:
- Not sure if working
- creates slower code (this may be a problem)

Notes:
Information about the flag can be found here: https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html

## **Elf relocation:**
Use the elf relocation sections for relocating.

Pro:
- Code still runs at the same speed
Con:
- Probably complex to implement correct

Notes:
No experience with this. Probably would take a look at brainslug. https://github.com/Chadderz121/brainslug-wii

# Tasks

At first I would try to get the position indenpendet code working, to have a solid base.

Position indenpendent code:
- [ ] Do some more research about the effects of PIC
- [ ] Create a sample application with position independent code
- [ ] Place it somewhere in RAM and check if it's still running
- [ ] Make some compatibility checks (with linked libs, more complex code etc.)

On a later point or/and when PIC is not feasable try to do elf relocation:

- [ ] Research
- [ ] Create base application
- [ ] Create relocation code
- [ ] Testing

# Notes:
The location also may vary with each Wii U FW version. Dependend on the avaiable and unused space.
@QuarkTheAwesome already worked on it iirc. Look at his code and see what can be used. Ask were where exactly problems.

**Comment by Maschell** [comment]
I spent some time on creating .elf with PIC, but it looks like you still need to relocate things like the .data section.
This is why I moved on an tried to re-implement/port the brainslug code, but still have issues.

**Comment by Maschell** [comment]
Using the elf relocation now. Brainslug is a really solid base. Working so far.
Only C++ is a problem, it doesn't seem to be compatible with the "relocatable" flag

**Comment by Maschell** [comment]
The plugins are using elf relocations are working great, no issues so far. Also the problem beeing not compatible with C++ has been solved.
I guess we now have our winner. Relocations!
(This part was way easiert than I though. Thanks Chadderz for brainslug <3)
