### ISSUE TITLE
Define a stable interface for the plugins

### ISSUE THREAD

**Issue by Maschell** [wiiu-env/WiiUPluginSystem#2]
# Problem
The plugins needs a interface they need to fulfill that will (hopefully) never change.

In general the plugin needs some sort of way to:
- tell which functions patch and how it should be patched
	- information about the rpl to patch
	- information about the function name.
	- the actual replacing code
- tell the current version (for update checking)
- provide general meta information
	- author
	- date
	- description

The plugin should be able to hook into serveral predefined functions:
- When the application start
- When the application ends
- On each frame
- When homemenu was opened
- ???

The plugin needs to be configurable.
- the loader needs some way of setting information
	- the plugin itself may need to be configured
		- like the controller mapping for hid to vpad
		- like the button combo for SwapDRC			
		- embed into the loader?
			- the plugin can somehow create a config within the loader.
				- using default gui elements.
				- some sort of generic, but intuitive interface for this.				
			- or the loader jumps into (graphical) config of the plugin
				- e.g. keep the current HID to VPAD gui and it can be access over the loader.
				- this would probably lead to big plugins due static linking (all apps with libgui support are at least 2MB)
				
# Overview
So the simplefied overview would be:

- (De)-Init
- Configuration
- Provide (meta) information
- Patch function
- Hooks

# Advanced function patching.
The function patching could also be extended by extra infos:
- Provide the parameter/result of the original function call
- Provide the parameter/result of the previous function call

# Task

- [ ] Define hook-methods names/signature for the (de)init and "on each frame" method.
- [ ] Brainstorm more hook possibilties
- [ ] Brainstorm about the configuration
- [ ] Which information is needed for function patching
- [ ] How would patching a function of a (game) .rpx would look like?
- [ ] Discuss if the advanced function patching is needed.
- [ ] Make sure the interface is really stable.

# Notes
maybe incomplete

**Comment by Maschell** [comment]
With commit https://github.com/Maschell/WiiUPluginSystem/commit/d64f221a9256f7b8cbfcce3fe5efaa6b86ed9e80 new meta data what added to the plugin.
Now we have the datetime from when the plugin was compiled. This can be an indicator if the plugin was updated ?!?! Maybe in combination with "version" metatag.
Would it be an feasible option, to add something like "revision" which needs to be incremented on each update which is noticeable for the user?
