### ISSUE TITLE
Find a place to store the plugins

### ISSUE THREAD

**Issue by Maschell** [wiiu-env/WiiUPluginSystem#3]
# Problem
The plugins need to be loaded in memory at some place that survives.
Even after loading multiple games and also memory consuming games like Zelda BOTW, the plugin should be still in memory.

@dimok789 already found places that will be used for loadiine:
https://github.com/dimok789/loadiine_gx2/blob/master/src/game/memory_area_table.c
It needs to be confirmend, that these areas are really unused.

# Tasks

- [ ] Check/guess how much space the plugins may need
- [ ] Find places in memory that are unused
- [ ] Make sure they are really unused.
- [ ] Add mechanism to store/load the plugins

**Comment by Maschell** [comment]
Currently the plugins (+loader) are stored in the area where the HBL stores it's binaries.
This mean currently we can't use the plugin system together with other homebrew applications.
At the time of writing this, the loader takes up ~ 2,5MB, leaves space for 5,6MB plugins. 
The biggest plugin so far takes up like 200kb. 
Beside of not beeing compatible with homebrew, everything should be fine.

**Comment by downloadpizza** [comment]
You could make hbc as a plugin, don't know how big it is tho
